# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'modul_19.4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for modul_19.4
  pod 'SnapKit', '~> 5.0.1'
  pod 'Alamofire'

end
